config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path
from .views import report,upload,import_data,details_report,comment,date_report,compare_report

app_name='web'
urlpatterns = [
    path('', report ,name='report'),
    path('upload/', upload,name='upload'),
    path('details_report/', details_report,name='details_report'),
    path('comment/', comment,name='comment'),
    path('compare_report/', compare_report,name='compare_report'),
    path('date_report/', date_report,name='date_report'),


   
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

web/models.py
from django.db import models
import datetime
from account.models import User

# Create your models here.



class GurdInfo(models.Model):
    name=models.CharField('نام',max_length=50)
    # l_name=models.CharField('نام خانوادگی',max_length=50)
    # d_name=models.CharField('نام پدر',max_length=50)
    # id_num=models.CharField('شماره شناسنامه',max_length=50)
    # id_code=models.CharField('کد ملی',max_length=50)
    # sex=models.CharField('جنسیت',max_length=10)
    # b_date=models.DateField('تاریخ تولد')
    # p_birth=models.CharField('محل تولد',max_length=50)
    # thumbnail=models.ImageField(upload_to='media',null=True,blank=True)

    def __str__(self):
        return '{}  -   {}'.format(self.name )


class TourData(models.Model):
    name=models.CharField('نام',max_length=50)
    date=models.DateField()
    duration=models.IntegerField()
    number=models.IntegerField()
    upload_date=models.DateField('تاریخ آپلود',auto_now_add=True)

    class Meta:
        verbose_name = 'tour data'
        verbose_name_plural = 'tour data'

    def __str__(self):
        return '{}    {}'.format(self.name,self.date)

class Comment(models.Model):
    content=models.TextField('متن',)
    publisher=models.ForeignKey(User, verbose_name="کاربر", on_delete=models.CASCADE)
    publish_date=models.DateTimeField('تاریخ ثبت',auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.content)

web/forms.py
from django import forms

class CommentForm(forms.Form):
    content=forms.CharField(label='متن', widget=forms.Textarea(attrs={"rows":5, "cols":100}))
    

account/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView,LogoutView

# Create your views here.

class Login(LoginView):
    pass

class Logout(LogoutView):
    pass

web/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from web.reporter import analyzer,read_data
from.models import TourData,Comment
from django.db.models import Count,Sum
import datetime
import jdatetime
from .forms import CommentForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.

def report(request):
  

    comments=Comment.objects.filter(publish_date__gt=datetime.date.today()).order_by('-publish_date')

    left=[]
    height=[]   
    tour_data_query=TourData.objects.filter(upload_date=datetime.date.today())
    tour_data_groupby=tour_data_query.values('name').annotate(duration_sum=Sum('duration'))
    
    
    chart_data=tour_data_groupby.values_list('name','duration_sum')

    if tour_data_query:
        date=tour_data_query.values_list('date')[0][0]
    else :
        date=jdatetime.date.today()

    for i in chart_data:
        left.append(i[0])
        height.append(i[1])

    print(left)
    print(height)

    context={
            'labels':left,
            'data':height,
            'date':date,
            'comments':comments
            }
    return render(request,'web/report.html',context)

def import_data():

    tour_data=read_data()

    for row in tour_data:
        
        obj=TourData(name=row[1],date=row[2],duration=int(row[3]),number=row[4])

        obj.save()   



def upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile=request.FILES['myfile']
        fs=FileSystemStorage()
        fs.delete('1.xls')
        filename=fs.save('1.xls',myfile)
        try:
            analyzer()
            import_data()
            context={
                'message':'بارگذاری انجام گردید',
                'message_color':'success'
                    }
            
        except :
            context={
                'message':'بارگذاری  با خطا مواجه شد',
                'message_color':'danger'
            }
        

        return render(request,'web/upload.html',context)


    return render(request,'web/upload.html')


def details_report(request)  :

    left=[]
    height=[]

    if request.GET.get('gurd_name'):
        name=request.GET.get('gurd_name')

        tour_data_query=TourData.objects.filter(name__contains=name).order_by('date')

        tour_data_groupby=tour_data_query.values('date').annotate(duration_sum=Sum('duration'))


        chart_data=tour_data_groupby.values_list('date','duration_sum')
        
        for i in chart_data:
            left.append(i[0].strftime("%m-%d"))
            height.append(i[1])

        #calculating moving avarage
        N = 17
        cumsum, moving_aves = [0], []

        for i, x in enumerate(height, 1):
            cumsum.append(cumsum[i-1] + x)
            if i>=N:
                moving_ave = (cumsum[i] - cumsum[i-N])/N
                #can do stuff with moving_ave here
                moving_aves.append(int(moving_ave))


        context={
                'labels':left,
                'data':height,
                'name':name,
                'avarege':moving_aves
                }
        return render(request,'web/detail_report.html',context)


    return render(request,'web/detail_report.html')

@login_required   
def comment(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            obj=Comment()
            message=form.cleaned_data['content']
            obj.content=message
            obj.publisher=request.user
            obj.save()        
            
    
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('web:report'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CommentForm()

    return render(request, 'web/comment.html', {'form': form})   
 
def compare_report(request):
    return HttpResponse ('<h1>در دست ساخت</h1>')

def date_report(request):
    return HttpResponse ('<h1>در دست ساخت</h1>')

web/templates/web/_base.html
{% load static%}
<!DOCTYPE html>
<html lang="en-US">
<head>

<title>سامانه حراست</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href={% static 'web/css/index.css' %} > 
	
<link href='https://fonts.googleapis.com/css?family=Lalezar' rel='stylesheet'>
<link href="https://fonts.googleapis.com/css2?family=Markazi+Text:wght@500;600&display=swap" rel="stylesheet">

<div class='dropbox'>
    {% block dropbox %}
        <a class="btn btn-dark"  href={% url 'web:report' %} role="button" >صفحه اصلی</a>
    {% endblock dropbox %}
</div>

<h1 style='margin:30px;text-align: center;'>
    {% block page_titile %}
    گزارش گشت نگهبانی
    {% endblock page_titile %}
</h1>

<div class="col" > 
    

    {% block navbar %} {% endblock navbar %} 
    {% block tabel %} {% endblock tabel %}
    {% block main %} {% endblock main %}

    {% block chart1 %} {% endblock chart1 %}
    {% block chart2 %} {% endblock chart2 %}


    
</div>
</body>
</html>

web/templates/web/comment.html
{% extends 'web/_base.html' %}
{% load static %}


{% block page_titile %}
ثبت پیام
{% endblock page_titile %}

{% block main %}
<div class='comment'>
    <form action='' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-lg">ثبت</button>
       
    </form>
</div>

{% endblock main %}

web/templates/web/compare_report.html
{% extends 'web/_base.html' %}
{% load static %}


{% block page_titile %}
مقایسه عملکرد نگهبانان
{% endblock page_titile %}


{% block dropbox %} 

  <div class="dropdown">
    {{ block.super }}

    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      گزارش گیری
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href={% url 'web:details_report' %}>انفرادی</a>
      <a class="dropdown-item" href="#">مقایسه ای</a>
      <a class="dropdown-item" href="#">زمانی</a>
    </div>
  </div>

{% endblock dropbox %} 

web/templates/web/detail_report.html
{% extends 'web/_base.html' %}
{% load static %}

{% block page_titile %}
گزارش گشت زنی نگهبان
{% endblock page_titile %}

{% block dropbox %} 

  <div class="dropdown">
    {{ block.super }}

    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      گزارش گیری
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href={% url 'web:details_report' %}>انفرادی</a>
      <a class="dropdown-item" href="#">مقایسه ای</a>
      <a class="dropdown-item" href="#">زمانی</a>
    </div>
  </div>

{% endblock dropbox %} 



{% block navbar %} 
    <form method="GET" enctype="text/plain">

        <label for="gurd_name">نام نگهبان :</label>
        {% comment %} <input type="text" name="gurd_name"> {% endcomment %}
        <select name="gurd_name"  >

              <option value= 'میثم محمدی'>
              میثم محمدی
              </option>
              <option value='آسترکی'>
              آسترکی
              </option>
              <option value= 'حشمتی پور'>
              حشمتی پور
              </option>
              <option value= 'باجلان'>
              باجلان
              </option>
              <option value= 'مهرآبادی'>
              مهرآبادی
              </option>
              <option value= 'دولت آبادی'>
              دولت آبادی
              </option>
              <option value= 'چقایی'>
              چقایی
              </option>
              <option value= 'جودکی'>
              جودکی
              </option>
              <option value=  'خراط نژاد'>
              خراط نژاد
              </option>
                        <option value=  'حسینی'>
              حسینی
              </option>
                        <option value=  'ذوالفقاری'>
              ذوالفقاری
              </option>
                                  <option value=  'عظیم محمدی'>
              عظیم محمدی
              </option>

         

   
      </select>
        <button type="submit" > جستجو</button>
    
    </form>
{% endblock navbar %}


{% block main %}

<div class='date21'>
  <p  >
  نام نگهبان :
  {{name|safe}}
  </p>
</div>

 {% endblock main %}


{% block chart1 %}


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>


<div class="chart1" >
    <canvas id="bar-chart" ></canvas>
</div>

<script>


new Chart(document.getElementById("bar-chart"), {
    type: 'line',
    data: {
      labels: {{labels|safe}},
      datasets: [

        {
          label: "میانگین",
          backgroundColor: 'black',
          borderColor:'black',
          fill: false,
          pointRadius: 0, 
          data: {{avarege|safe}}
        },      
        {
          label: "گشت روزانه",
          backgroundColor: "#2550FF",
          data: {{data|safe}}
        },

      ]
    },
    options: {
      
      legend: { display: true },
      title: {
        display: true,
        text:  'نمودار مدت گشت زنی به دقیقه'
      }
    }
})

</script>
{% endblock chart1%}

web/templates/web/report.html
{% extends 'web/_base.html' %}
{% load static %}


{% block page_titile %}
 سامانه نگهبانی
{% endblock page_titile %}


{% block main %}

<h4 class="alert-dark" style="text-align: center;">گزارش روزانه</h4>

{% if comments %}
  <div class="comment">
    <div class="alert alert-dark" role="alert">
      
      {% for comment in comments%}
        
        <p>{{comment.content}}</p>
     
        <p>{{comment.publisher.first_name}} __  ساعت: {{comment.publish_date|date:"P"}} </p>
        <hr>
    
      {% endfor %}
      
    </div>
  </div>

{% else %}
<br>
<br>
<br>
{% endif%}

<div class='date21'>
  <h4 class="alert-dark" style="text-align: center;">
      نمودار گشت زنی مورخ  :
      {{date|date:" Y/m/d"}}
  </h4>

</div>

 {% endblock main %}

{% block dropbox %} 

  <div class="dropdown">

    <a class="btn btn-dark" href={% url 'web:upload' %} role="button">بارگذاری</a>
    <a class="btn btn-dark" href={% url 'web:comment' %} role="button">ثبت  گزارش </a>

    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      گزارش گیری
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href={% url 'web:details_report' %}>انفرادی</a>
      <a class="dropdown-item" href='#'>مقایسه ای</a>
      <a class="dropdown-item" href='#'>زمانی</a>
    </div>
</div>
{% endblock dropbox %}

{% block chart1 %}


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>


<div class="chart1" >
    <canvas id="bar-chart" ></canvas>
</div>

<script>
new Chart(document.getElementById("bar-chart"), {
    type: 'bar',
    data: {
      labels: {{labels|safe}},
      datasets: [
        {
          label: "دقیقه",
          backgroundColor: "#3A970E",
          data: {{data|safe}}
        },
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text:  'نمودار مدت گشت زنی به دقیقه'
      }
    }
})

</script>
{% endblock chart1%}

web/templates/web/upload.html
{% extends 'web/_base.html' %}
{% load static %}


{% block page_titile %}
بارگذاری فایل اکسل
{% endblock page_titile %}

{% block main %} 
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}
<label for="myfile">انتخاب فایل:</label>
<input type="file" name="myfile">
<button type="submit" > ارسال</button>

</form>

<br>
<br>
<br>
<div class="alert alert-{{message_color}}" role="alert">
    {{message}}
</div>

{% endblock main %}